### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by IdoFriedman1** [yarin177/Hafifa-Rolling-exercise#1]
צור erd בעזרת draw.io או כלי מתאים אחר ותשלח כאן בissue לאישור.

**Comment by yarin177** [comment]
![ERD drawio](https://user-images.githubusercontent.com/51924888/183289696-a8c08bad-daf3-4e39-baca-36e90ec1ec48.png)

**Comment by IdoFriedman1** [comment]
מה הם הpk וfk?

**Comment by IdoFriedman1** [comment]
חפש דוגמאוצ באינטרנט של erd ונסה לראות מה חסר

**Comment by yarin177** [comment]
![ERD drawio (2)](https://user-images.githubusercontent.com/51924888/183292146-e0885d5f-9cf3-4510-9d3c-1c9b4de942fd.png)

**Comment by IdoFriedman1** [comment]
מה הpk של הפריים?
ולמה שהpk של הסרטון לא יהיה הנתיב שלו? זה יחודי

**Comment by yarin177** [comment]
![ERD drawio (3)](https://user-images.githubusercontent.com/51924888/183292952-7e59c043-8d4b-4d75-9e61-15f4548f68e1.png)

**Comment by IdoFriedman1** [comment]
אם יש שני סרטונים משמע שיש שאני פריימים שאינדקס שלהם הוא 1 בסרטון, שים את הנתיב לפריים כpk

**Comment by IdoFriedman1** [comment]
Iועכשיו אין video id יש נתיב
אז תשנה את הfk בפריים מid לos path

**Comment by yarin177** [comment]
![ERD drawio (7)](https://user-images.githubusercontent.com/51924888/183293605-ef091f93-f071-4fc5-99c9-2c88a91f2329.png)

**Comment by IdoFriedman1** [comment]
אש

**Comment by IdoFriedman1** [comment]
אה רגע

**Comment by IdoFriedman1** [comment]
הקשר בין פריים למטאדאטא הפוך

**Comment by IdoFriedman1** [comment]
יכול להיות כמה פריימים עם אותו מטאדאטא לא הפוך

**Comment by IdoFriedman1** [comment]
וזהו

**Comment by IdoFriedman1** [comment]
אחרי זה סגור את הissue

**Comment by yarin177** [comment]
![ERD drawio (8)](https://user-images.githubusercontent.com/51924888/183293988-e7136c32-bd6e-42e5-a1d4-1ca50c2a0985.png)
